[package]
name = "sicql-fs"
description = "Crate responsible for storing SicQL database file system"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
