[package]
name = "sicql-compiler"
description = "Compiler for SicQL dialect"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
